import projectDebugDefaults from '../../data/debug_defaults.json'

// ============================================================
// debugConfig — 可运行时调整的调试参数
// 存储：localStorage（key 前缀 bigbazzar_cfg_）
// 实时同步：BroadcastChannel（bigbazzar_debug）
//
// 游戏侧：调用 getConfig() / 订阅 onConfigChange()
// 调试页侧：调用 setConfig() 即可同步到正在运行的游戏
// ============================================================

const STORAGE_PREFIX = 'bigbazzar_cfg_'
const BC_NAME        = 'bigbazzar_debug'

function normalizeConfigNumber(key: string, value: number, def?: ConfigDef): number {
  const d = def ?? CONFIG_DEFS[key]
  let v = Number.isFinite(value) ? value : (d?.defaultValue ?? 0)
  if (d) v = Math.max(d.min, Math.min(d.max, v))

  // 约定：所有字号统一为 4 的倍数
  if (key.endsWith('FontSize')) {
    v = Math.round(v / 4) * 4
    if (d) v = Math.max(d.min, Math.min(d.max, v))
  }
  return v
}

// ---- 参数定义 ----

export interface ConfigDef {
  labelCn:       string    // 中文标签
  description:   string    // 说明文字
  defaultValue:  number
  min:           number
  max:           number
  step:          number
  unit:          string    // 显示单位（px / ms 等）
}

export const CONFIG_DEFS: Record<string, ConfigDef> = {
  dragThresholdPx: {
    labelCn:      '触发拖拽的最小移动距离',
    description:  '手指移动超过此距离触发拖拽，低于则视为点击',
    defaultValue: 12,
    min:  2,
    max:  80,
    step: 1,
    unit: 'px',
  },
  dragYOffset: {
    labelCn:      '拖拽时物品向上偏移量',
    description:  '负值 = 物品显示在手指上方，让手指不遮挡物品',
    defaultValue: -80,
    min:  -240,
    max:  0,
    step: 4,
    unit: 'px',
  },
  shopItemScale: {
    labelCn:      '商店物品缩放',
    description:  '商店物品显示缩放（1=100%）',
    defaultValue: 0.9,
    min:  0.5,
    max:  1.2,
    step: 0.01,
    unit: 'x',
  },
  battleItemScale: {
    labelCn:      '战斗区物品缩放',
    description:  '我方战斗区与背包物品显示缩放（1=100%）',
    defaultValue: 1,
    min:  0.5,
    max:  1.2,
    step: 0.01,
    unit: 'x',
  },
  battleItemScaleBackpackOpen: {
    labelCn:      '背包打开时我方缩放',
    description:  '打开背包时我方战斗区与相关信息缩放（1=100%）',
    defaultValue: 1,
    min:  0.5,
    max:  1.2,
    step: 0.01,
    unit: 'x',
  },
  enemyAreaScale: {
    labelCn:      '敌方区域缩放',
    description:  '敌方战斗区（含物品）缩放',
    defaultValue: 0.8,
    min:  0.5,
    max:  1.2,
    step: 0.01,
    unit: 'x',
  },
  enemyHpBarScale: {
    labelCn:      '敌方血条缩放',
    description:  '敌方血条与血条文字缩放（1=100%）',
    defaultValue: 1,
    min:  0.5,
    max:  1.2,
    step: 0.01,
    unit: 'x',
  },
  snapBackMs: {
    labelCn:      '放置失败弹回动画时长',
    description:  '物品放置失败时弹回原位的动画时长',
    defaultValue: 150,
    min:  30,
    max:  600,
    step: 10,
    unit: 'ms',
  },
  squeezeMs: {
    labelCn:      '挤出动画时长',
    description:  '挤出其他物品腾出空位的滑动动画时长（新挤出会打断旧动画）',
    defaultValue: 120,
    min:  20,
    max:  400,
    step: 10,
    unit: 'ms',
  },
  squeezePreviewDelayMs: {
    labelCn:      '挤出预览触发延迟',
    description:  '拖动时悬停多少毫秒后预览挤出效果（0=立即预览）',
    defaultValue: 300,
    min:  0,
    max:  1000,
    step: 50,
    unit: 'ms',
  },
  dragSqueezeEnabled: {
    labelCn:      '拖拽挤出开关',
    description:  '1=开启挤出；0=关闭挤出（仅保留合成与换位）',
    defaultValue: 1,
    min:  0,
    max:  1,
    step: 1,
    unit: 'bool',
  },
  transferToBackpackAnimMs: {
    labelCn:      '顶回背包飞行动画时长',
    description:  '战斗区物品被顶回背包时，飞向小黄格的动画总时长',
    defaultValue: 220,
    min:  80,
    max:  800,
    step: 10,
    unit: 'ms',
  },
  transferToBackpackArcY: {
    labelCn:      '顶回背包飞行弧高',
    description:  '飞入背包动画的弧线高度（越大越上拱）',
    defaultValue: 46,
    min:  0,
    max:  220,
    step: 2,
    unit: 'px',
  },
  transferToBackpackIconScale: {
    labelCn:      '顶回背包图标起始缩放',
    description:  '飞行动画中图标初始大小倍率（相对默认图标）',
    defaultValue: 0.82,
    min:  0.3,
    max:  1.4,
    step: 0.02,
    unit: 'x',
  },
  transferToBackpackMorphStartPct: {
    labelCn:      '顶回背包转黄格起点',
    description:  '飞行动画进行到该比例后开始从图标过渡到小黄格',
    defaultValue: 0.55,
    min:  0.1,
    max:  0.95,
    step: 0.01,
    unit: 'ratio',
  },
  transferToBackpackHoldMs: {
    labelCn:      '顶回背包黄格停留时长',
    description:  '小黄格落点后停留再淡出的时长',
    defaultValue: 120,
    min:  0,
    max:  600,
    step: 10,
    unit: 'ms',
  },
  synthFadeOutMs: {
    labelCn:      '合成淡出时长',
    description:  '命中合成后，被吞并的拖拽物品淡出消失时长',
    defaultValue: 120,
    min:  0,
    max:  800,
    step: 10,
    unit: 'ms',
  },
  synthHoldMs: {
    labelCn:      '合成停留时长',
    description:  '合成信息层完全显示后停留多久再开始淡出',
    defaultValue: 260,
    min:  0,
    max:  2000,
    step: 20,
    unit: 'ms',
  },
  crossSynthesisCarouselSpeedPx: {
    labelCn:      '跨职合成走马灯速度',
    description:  '跨物品合成确认弹窗中候选卡片横向滚动速度（0=静止）',
    defaultValue: 170,
    min:  0,
    max:  480,
    step: 5,
    unit: 'px/s',
  },
  shopAreaX: {
    labelCn:      '商店区 X 坐标',
    description:  '商店面板左上角 X 坐标',
    defaultValue: 0,
    min:  -200,
    max:  200,
    step: 1,
    unit: 'px',
  },
  shopAreaY: {
    labelCn:      '商店区 Y 坐标',
    description:  '商店面板左上角 Y 坐标',
    defaultValue: 430,
    min:  0,
    max:  1300,
    step: 2,
    unit: 'px',
  },
  battleZoneX: {
    labelCn:      '战斗区 X 坐标',
    description:  '战斗区左上角 X 坐标',
    defaultValue: 0,
    min:  -200,
    max:  200,
    step: 1,
    unit: 'px',
  },
  battleZoneY: {
    labelCn:      '战斗区 Y 坐标',
    description:  '战斗区左上角 Y 坐标',
    defaultValue: 1020,
    min:  0,
    max:  1300,
    step: 2,
    unit: 'px',
  },
  battleZoneYInBattleOffset: {
    labelCn:      '战斗场景我方战斗区Y偏移',
    description:  '仅战斗场景生效：在 battleZoneY 基础上的附加偏移',
    defaultValue: 0,
    min:  -300,
    max:  1000,
    step: 1,
    unit: 'px',
  },
  enemyBattleZoneY: {
    labelCn:      '敌方战斗区 Y 坐标',
    description:  '敌方战斗区左上角 Y 坐标',
    defaultValue: 180,
    min:  0,
    max:  1300,
    step: 2,
    unit: 'px',
  },
  enemyHpBarY: {
    labelCn:      '敌方血条 Y 坐标',
    description:  '敌方生命条容器左上角 Y 坐标',
    defaultValue: 470,
    min:  0,
    max:  1300,
    step: 2,
    unit: 'px',
  },
  playerHpBarY: {
    labelCn:      '我方血条 Y 坐标',
    description:  '我方生命条容器左上角 Y 坐标',
    defaultValue: 920,
    min:  0,
    max:  1300,
    step: 2,
    unit: 'px',
  },
  battleHpBarH: {
    labelCn:      '战斗血条高度',
    description:  '战斗双方生命进度条高度',
    defaultValue: 28,
    min:  8,
    max:  80,
    step: 1,
    unit: 'px',
  },
  battleHpBarRadius: {
    labelCn:      '战斗血条圆角',
    description:  '战斗双方生命进度条圆角',
    defaultValue: 12,
    min:  0,
    max:  40,
    step: 1,
    unit: 'px',
  },
  battleHpBarWidth: {
    labelCn:      '战斗血条宽度',
    description:  '战斗双方生命进度条宽度',
    defaultValue: 560,
    min:  240,
    max:  620,
    step: 2,
    unit: 'px',
  },
  battleHpTextFontSize: {
    labelCn:      '战斗血条字号',
    description:  '战斗阶段血条文本字体大小',
    defaultValue: 20,
    min:  10,
    max:  56,
    step: 1,
    unit: 'px',
  },
  battleTextFontSizeDamage: {
    labelCn:      '普通伤害跳字字号',
    description:  '战斗中普通伤害/状态伤害跳字字体大小',
    defaultValue: 24,
    min:  10,
    max:  80,
    step: 1,
    unit: 'px',
  },
  battleTextFontSizeCrit: {
    labelCn:      '暴击伤害跳字字号',
    description:  '战斗中暴击伤害跳字字体大小',
    defaultValue: 32,
    min:  10,
    max:  96,
    step: 1,
    unit: 'px',
  },
  battleStatusTimerFontSize: {
    labelCn:      '状态计时字号',
    description:  '战斗卡牌上状态持续时间数字字号',
    defaultValue: 20,
    min:  8,
    max:  64,
    step: 4,
    unit: 'px',
  },
  battleFirePulseScaleMax: {
    labelCn:      '开火放缩最大值',
    description:  '物品触发开火时的最大放缩倍率',
    defaultValue: 1.12,
    min:  1,
    max:  1.8,
    step: 0.01,
    unit: 'x',
  },
  battleFirePulseMs: {
    labelCn:      '开火放缩时长',
    description:  '物品触发开火时放缩与回弹总时长',
    defaultValue: 180,
    min:  40,
    max:  1200,
    step: 10,
    unit: 'ms',
  },
  battleProjectileFlyMs: {
    labelCn:      '飞点飞行时长',
    description:  '伤害/护盾飞点从物品到血条中心的飞行时长',
    defaultValue: 180,
    min:  40,
    max:  1200,
    step: 10,
    unit: 'ms',
  },
  battleProjectileFlyMsMin: {
    labelCn:      '飞点时长最小值',
    description:  '飞点飞行时长随机区间下限',
    defaultValue: 140,
    min:  40,
    max:  1200,
    step: 10,
    unit: 'ms',
  },
  battleProjectileFlyMsMax: {
    labelCn:      '飞点时长最大值',
    description:  '飞点飞行时长随机区间上限',
    defaultValue: 220,
    min:  40,
    max:  1200,
    step: 10,
    unit: 'ms',
  },
  battleProjectileItemSizePx: {
    labelCn:      '图标子弹尺寸',
    description:  '图标子弹的基础尺寸（像素）',
    defaultValue: 68,
    min:  16,
    max:  220,
    step: 1,
    unit: 'px',
  },
  battleProjectileArcHeight: {
    labelCn:      '子弹抛物线高度',
    description:  '子弹飞行的上拱高度（0 为直线）',
    defaultValue: 28,
    min:  0,
    max:  180,
    step: 1,
    unit: 'px',
  },
  battleProjectileSideArcMax: {
    labelCn:      '子弹左右最大弧度',
    description:  '飞行时沿左右方向随机偏移的最大弧度',
    defaultValue: 40,
    min:  0,
    max:  220,
    step: 1,
    unit: 'px',
  },
  battleProjectileScaleStart: {
    labelCn:      '子弹起始缩放',
    description:  '子弹飞行开始时的缩放倍率',
    defaultValue: 0.9,
    min:  0.1,
    max:  3,
    step: 0.01,
    unit: 'x',
  },
  battleProjectileScalePeak: {
    labelCn:      '子弹峰值缩放',
    description:  '子弹飞行过程中的最大缩放倍率',
    defaultValue: 1.12,
    min:  0.1,
    max:  3,
    step: 0.01,
    unit: 'x',
  },
  battleProjectileScaleEnd: {
    labelCn:      '子弹结束缩放',
    description:  '子弹到达目标前的缩放倍率',
    defaultValue: 0.92,
    min:  0.1,
    max:  3,
    step: 0.01,
    unit: 'x',
  },
  battleProjectileScalePeakT: {
    labelCn:      '峰值出现时机',
    description:  '飞行进度中达到峰值缩放的时机（0~1）',
    defaultValue: 0.45,
    min:  0.05,
    max:  0.95,
    step: 0.01,
    unit: '',
  },
  battleProjectileSpinDegPerSec: {
    labelCn:      '子弹左旋速度',
    description:  '可旋转飞行物品子弹的向左旋转角速度（度/秒）',
    defaultValue: 360,
    min:  0,
    max:  2160,
    step: 10,
    unit: 'deg/s',
  },
  battleMulticastVisualGapMs: {
    labelCn:      '连发表现间隔',
    description:  '同一武器多段命中时，纯表现层的发射间隔（不影响结算）',
    defaultValue: 100,
    min:  0,
    max:  1000,
    step: 10,
    unit: 'ms',
  },
  battleStatusTextStrokeWidth: {
    labelCn:      '状态计时描边宽度',
    description:  '状态计时文字黑色描边宽度',
    defaultValue: 2,
    min:  0,
    max:  8,
    step: 1,
    unit: 'px',
  },
  battleStatusBadgePadX: {
    labelCn:      '状态底板水平内边距',
    description:  '状态计时底板左右内边距',
    defaultValue: 10,
    min:  0,
    max:  40,
    step: 1,
    unit: 'px',
  },
  battleStatusBadgePadY: {
    labelCn:      '状态底板垂直内边距',
    description:  '状态计时底板上下内边距',
    defaultValue: 4,
    min:  0,
    max:  24,
    step: 1,
    unit: 'px',
  },
  battleStatusBadgeRadius: {
    labelCn:      '状态底板圆角',
    description:  '状态计时底板圆角半径',
    defaultValue: 6,
    min:  0,
    max:  24,
    step: 1,
    unit: 'px',
  },
  battleStatusBadgeMinWidth: {
    labelCn:      '状态底板最小宽',
    description:  '状态计时底板最小宽度',
    defaultValue: 46,
    min:  20,
    max:  120,
    step: 1,
    unit: 'px',
  },
  battleStatusBadgeAlpha: {
    labelCn:      '状态底板透明度',
    description:  '状态计时底板透明度',
    defaultValue: 0.9,
    min:  0.1,
    max:  1,
    step: 0.01,
    unit: '',
  },
  battleStatusHasteYFactor: {
    labelCn:      '加速Y比例',
    description:  '加速计时在卡牌高度中的比例位置',
    defaultValue: 0.18,
    min:  0,
    max:  1,
    step: 0.01,
    unit: '',
  },
  battleStatusHasteOffsetY: {
    labelCn:      '加速Y偏移',
    description:  '加速计时额外垂直偏移',
    defaultValue: 0,
    min:  -80,
    max:  80,
    step: 1,
    unit: 'px',
  },
  battleStatusSlowYFactor: {
    labelCn:      '减速Y比例',
    description:  '减速计时在卡牌高度中的比例位置',
    defaultValue: 0.82,
    min:  0,
    max:  1,
    step: 0.01,
    unit: '',
  },
  battleStatusSlowOffsetY: {
    labelCn:      '减速Y偏移',
    description:  '减速计时额外垂直偏移',
    defaultValue: 0,
    min:  -80,
    max:  80,
    step: 1,
    unit: 'px',
  },
  battleStatusFreezeYFactor: {
    labelCn:      '冻结Y比例',
    description:  '冻结计时在卡牌高度中的比例位置',
    defaultValue: 0.5,
    min:  0,
    max:  1,
    step: 0.01,
    unit: '',
  },
  battleStatusFreezeOffsetY: {
    labelCn:      '冻结Y偏移',
    description:  '冻结计时额外垂直偏移',
    defaultValue: 0,
    min:  -80,
    max:  80,
    step: 1,
    unit: 'px',
  },
  battleFreezeOverlayAlpha: {
    labelCn:      '冻结遮罩透明度',
    description:  '冻结时覆盖整张卡牌的白色遮罩透明度',
    defaultValue: 0.32,
    min:  0,
    max:  1,
    step: 0.01,
    unit: '',
  },
  battleDamageFloatRandomX: {
    labelCn:      '伤害数字随机X范围',
    description:  '伤害数字初始位置随机左右偏移范围（±）',
    defaultValue: 14,
    min:  0,
    max:  120,
    step: 1,
    unit: 'px',
  },
  battleDamageFloatRiseMs: {
    labelCn:      '伤害数字上升时长',
    description:  '伤害数字从起点上升到目标高度的时长',
    defaultValue: 260,
    min:  20,
    max:  2000,
    step: 10,
    unit: 'ms',
  },
  battleDamageFloatRiseY: {
    labelCn:      '伤害数字上升高度',
    description:  '伤害数字上升位移高度',
    defaultValue: 46,
    min:  0,
    max:  240,
    step: 1,
    unit: 'px',
  },
  battleDamageFloatHoldMs: {
    labelCn:      '伤害数字停留时长',
    description:  '伤害数字上升结束后停留时长',
    defaultValue: 90,
    min:  0,
    max:  1200,
    step: 10,
    unit: 'ms',
  },
  battleDamageFloatFadeMs: {
    labelCn:      '伤害数字渐隐时长',
    description:  '伤害数字消失渐隐时长',
    defaultValue: 260,
    min:  20,
    max:  2000,
    step: 10,
    unit: 'ms',
  },
  battleEnemyPortraitWidthRatio: {
    labelCn:      '敌方立绘宽度比例',
    description:  '敌方立绘目标宽度占画布宽度比例',
    defaultValue: 0.56,
    min:  0.2,
    max:  1,
    step: 0.01,
    unit: 'ratio',
  },
  battleEnemyPortraitOffsetY: {
    labelCn:      '敌方立绘下移偏移',
    description:  '敌方立绘相对敌方血条下方的偏移',
    defaultValue: 18,
    min:  -80,
    max:  260,
    step: 1,
    unit: 'px',
  },
  battleEnemyPortraitHitYFactor: {
    labelCn:      '敌方立绘受击点比例',
    description:  '飞点命中敌方立绘的Y比例（0=顶部，1=底部）',
    defaultValue: 0.42,
    min:  0,
    max:  1,
    step: 0.01,
    unit: 'ratio',
  },
  battleEnemyPortraitHitScaleMax: {
    labelCn:      '敌方立绘受击放缩',
    description:  '敌方立绘受击时的最大放缩倍率',
    defaultValue: 1.1,
    min:  1,
    max:  1.8,
    step: 0.01,
    unit: 'x',
  },
  battleEnemyPortraitHitPulseMs: {
    labelCn:      '敌方立绘受击时长',
    description:  '敌方立绘受击放缩与回弹总时长',
    defaultValue: 140,
    min:  20,
    max:  1200,
    step: 10,
    unit: 'ms',
  },
  battleEnemyPortraitIdleLoopMs: {
    labelCn:      '敌方立绘呼吸周期',
    description:  '敌方立绘默认循环放缩的周期时长',
    defaultValue: 1600,
    min:  200,
    max:  10000,
    step: 20,
    unit: 'ms',
  },
  battleEnemyPortraitIdleScaleMax: {
    labelCn:      '敌方立绘呼吸最大缩放',
    description:  '敌方立绘默认循环放缩的最大倍率',
    defaultValue: 1.03,
    min:  1,
    max:  1.3,
    step: 0.005,
    unit: 'x',
  },
  battleEnemyPortraitFlashMs: {
    labelCn:      '敌方立绘闪白时长',
    description:  '敌方立绘受击闪白衰减时长',
    defaultValue: 120,
    min:  20,
    max:  2000,
    step: 10,
    unit: 'ms',
  },
  battleEnemyPortraitFlashColor: {
    labelCn:      '敌方立绘闪白颜色',
    description:  '敌方立绘受击闪白叠层颜色（16进制）',
    defaultValue: 0xffffff,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleEnemyPortraitFlashAlpha: {
    labelCn:      '敌方立绘闪白强度',
    description:  '敌方立绘受击闪白叠层透明度',
    defaultValue: 0.55,
    min:  0,
    max:  1,
    step: 0.01,
    unit: '',
  },
  battleEnemyPortraitDeathFadeMs: {
    labelCn:      '敌方立绘死亡淡出时长',
    description:  '敌方死亡后立绘半透消失时长',
    defaultValue: 600,
    min:  60,
    max:  3000,
    step: 10,
    unit: 'ms',
  },
  battlePlayerPortraitWidthRatio: {
    labelCn:      '我方立绘宽度比例',
    description:  '我方立绘目标宽度占画布宽度比例',
    defaultValue: 0.42,
    min:  0.2,
    max:  2,
    step: 0.01,
    unit: 'ratio',
  },
  battlePlayerPortraitOffsetY: {
    labelCn:      '我方立绘上移偏移',
    description:  '我方立绘相对画布底部的偏移（正值上移）',
    defaultValue: 6,
    min:  -120,
    max:  320,
    step: 1,
    unit: 'px',
  },
  battlePlayerPortraitHitYFactor: {
    labelCn:      '我方立绘受击点比例',
    description:  '飞点命中我方立绘的Y比例（0=顶部，1=底部）',
    defaultValue: 0.42,
    min:  0,
    max:  1,
    step: 0.01,
    unit: 'ratio',
  },
  battlePlayerPortraitHitScaleMax: {
    labelCn:      '我方立绘受击放缩',
    description:  '我方立绘受击时的最大放缩倍率',
    defaultValue: 1.1,
    min:  1,
    max:  1.8,
    step: 0.01,
    unit: 'x',
  },
  battlePlayerPortraitHitPulseMs: {
    labelCn:      '我方立绘受击时长',
    description:  '我方立绘受击放缩与回弹总时长',
    defaultValue: 140,
    min:  20,
    max:  1200,
    step: 10,
    unit: 'ms',
  },
  battlePlayerPortraitIdleLoopMs: {
    labelCn:      '我方立绘呼吸周期',
    description:  '我方立绘默认循环放缩的周期时长',
    defaultValue: 1600,
    min:  200,
    max:  10000,
    step: 20,
    unit: 'ms',
  },
  battlePlayerPortraitIdleScaleMax: {
    labelCn:      '我方立绘呼吸最大缩放',
    description:  '我方立绘默认循环放缩的最大倍率',
    defaultValue: 1.03,
    min:  1,
    max:  1.3,
    step: 0.005,
    unit: 'x',
  },
  battlePlayerPortraitFlashMs: {
    labelCn:      '我方立绘闪白时长',
    description:  '我方立绘受击闪白衰减时长',
    defaultValue: 120,
    min:  20,
    max:  2000,
    step: 10,
    unit: 'ms',
  },
  battlePlayerPortraitFlashColor: {
    labelCn:      '我方立绘闪白颜色',
    description:  '我方立绘受击闪白叠层颜色（16进制）',
    defaultValue: 0xffffff,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battlePlayerPortraitFlashAlpha: {
    labelCn:      '我方立绘闪白强度',
    description:  '我方立绘受击闪白叠层透明度',
    defaultValue: 0.55,
    min:  0,
    max:  1,
    step: 0.01,
    unit: '',
  },
  gameplayBurnTickMs: {
    labelCn:      '灼烧结算间隔',
    description:  '灼烧每次结算的时间间隔',
    defaultValue: 500,
    min:  100,
    max:  5000,
    step: 50,
    unit: 'ms',
  },
  gameplayPoisonTickMs: {
    labelCn:      '中毒结算间隔',
    description:  '中毒每次结算的时间间隔',
    defaultValue: 1000,
    min:  100,
    max:  5000,
    step: 50,
    unit: 'ms',
  },
  gameplayRegenTickMs: {
    labelCn:      '生命回复结算间隔',
    description:  '生命回复每次结算的时间间隔',
    defaultValue: 1000,
    min:  100,
    max:  5000,
    step: 50,
    unit: 'ms',
  },
  gameplayFatigueStartMs: {
    labelCn:      '超时扣血开始时间',
    description:  '战斗经过该时长后开始进入自动扣血阶段（不暂停物品CD）',
    defaultValue: 25000,
    min:  1000,
    max:  120000,
    step: 100,
    unit: 'ms',
  },
  gameplayFatigueTickMs: {
    labelCn:      '超时扣血Tick',
    description:  '自动扣血阶段每次结算伤害的时间间隔',
    defaultValue: 100,
    min:  50,
    max:  5000,
    step: 50,
    unit: 'ms',
  },
  gameplayFatigueBaseValue: {
    labelCn:      '超时扣血初始值',
    description:  '扣血基础值（每跳伤害=基础值*2^n）',
    defaultValue: 1,
    min:  1,
    max:  1000,
    step: 1,
    unit: '',
  },
  gameplayFatigueDoubleEveryMs: {
    labelCn:      '超时扣血翻倍间隔',
    description:  '每经过该时长，超时扣血伤害翻倍一次',
    defaultValue: 1000,
    min:  100,
    max:  20000,
    step: 100,
    unit: 'ms',
  },
  gameplayBurnShieldFactor: {
    labelCn:      '灼烧对盾系数',
    description:  '灼烧对护盾生效系数（0.5=伤盾减半）',
    defaultValue: 0.5,
    min:  0,
    max:  2,
    step: 0.01,
    unit: 'x',
  },
  gameplayBurnDecayPct: {
    labelCn:      '灼烧衰减比例',
    description:  '每次灼烧结算后层数衰减比例',
    defaultValue: 0.05,
    min:  0,
    max:  1,
    step: 0.01,
    unit: '',
  },
  gameplayHealCleansePct: {
    labelCn:      '治疗净化比例',
    description:  '直接治疗时净化灼烧/中毒层数比例',
    defaultValue: 0.05,
    min:  0,
    max:  1,
    step: 0.01,
    unit: '',
  },
  gameplayGrantAllClassItems: {
    labelCn:      '开局发放职业全套',
    description:  '1=职业选择后发放该职业全部装备（按各自最低品质）；0=仅发放默认两件',
    defaultValue: 0,
    min:  0,
    max:  1,
    step: 1,
    unit: '',
  },
  gameplayShowSpeedButton: {
    labelCn:      '战斗倍速按钮开关',
    description:  '1=显示战斗倍速按钮；0=隐藏',
    defaultValue: 0,
    min:  0,
    max:  1,
    step: 1,
    unit: '',
  },
  gameplayCrossSynthesisConfirm: {
    labelCn:      '跨物品合成二次确认',
    description:  '1=不同物品合成弹出确认；0=直接合成',
    defaultValue: 1,
    min:  0,
    max:  1,
    step: 1,
    unit: '',
  },
  gameplayBattleZoneNoSynthesis: {
    labelCn:      '上阵区禁止合成',
    description:  '1=上阵区仅挤出/换位且拖拽时背包显示合成箭头；0=关闭该逻辑',
    defaultValue: 1,
    min:  0,
    max:  1,
    step: 1,
    unit: '',
  },
  gameplaySameArchetypeDiffItemStoneSynthesis: {
    labelCn:      '同职异物合成转职石化',
    description:  '1=同职业不同物品合成走2选1并升1级；0=保持随机合成',
    defaultValue: 1,
    min:  0,
    max:  1,
    step: 1,
    unit: '',
  },
  gameplayShowSimpleDescriptions: {
    labelCn:      '显示简版描述',
    description:  '1=保留简版->详细版切换；0=所有物品/技能描述默认显示详细版',
    defaultValue: 0,
    min:  0,
    max:  1,
    step: 1,
    unit: '',
  },
  gameplaySkillDraftRerollEnabled: {
    labelCn:      '技能选择可刷新',
    description:  '1=技能选择界面显示并允许刷新；0=不允许刷新',
    defaultValue: 0,
    min:  0,
    max:  1,
    step: 1,
    unit: '',
  },
  gameplayEventDraftRerollEnabled: {
    labelCn:      '事件选择可刷新',
    description:  '1=事件选择界面显示并允许刷新；0=不允许刷新',
    defaultValue: 0,
    min:  0,
    max:  1,
    step: 1,
    unit: '',
  },
  enemyDraftEnabled: {
    labelCn:      '敌方实验AI开关',
    description:  '1=启用敌方购买/合成实验逻辑；0=沿用原有模板优先逻辑',
    defaultValue: 0,
    min:  0,
    max:  1,
    step: 1,
    unit: '',
  },
  enemyDraftSameArchetypeBias: {
    labelCn:      '同职业倾向',
    description:  '敌方生成时偏向同职业的概率（0~1）',
    defaultValue: 0.85,
    min:  0,
    max:  1,
    step: 0.01,
    unit: '',
  },
  backpackZoneX: {
    labelCn:      '背包区 X 坐标',
    description:  '背包区左上角 X 坐标',
    defaultValue: 0,
    min:  -200,
    max:  200,
    step: 1,
    unit: 'px',
  },
  backpackZoneY: {
    labelCn:      '背包区 Y 坐标',
    description:  '背包区左上角 Y 坐标',
    defaultValue: 430,
    min:  0,
    max:  1300,
    step: 2,
    unit: 'px',
  },
  backpackBtnX: {
    labelCn:      '背包按钮 X 坐标',
    description:  '背包按钮圆心 X 坐标',
    defaultValue: 80,
    min:  -100,
    max:  740,
    step: 1,
    unit: 'px',
  },
  backpackBtnY: {
    labelCn:      '背包按钮 Y 坐标',
    description:  '背包按钮圆心 Y 坐标',
    defaultValue: 900,
    min:  0,
    max:  1384,
    step: 2,
    unit: 'px',
  },
  sellBtnX: {
    labelCn:      '出售按钮 X 坐标',
    description:  '出售按钮圆心 X 坐标',
    defaultValue: 560,
    min:  -100,
    max:  740,
    step: 1,
    unit: 'px',
  },
  sellBtnY: {
    labelCn:      '出售按钮 Y 坐标',
    description:  '出售按钮圆心 Y 坐标',
    defaultValue: 900,
    min:  0,
    max:  1384,
    step: 2,
    unit: 'px',
  },
  refreshBtnX: {
    labelCn:      '刷新按钮 X 坐标',
    description:  '刷新按钮圆心 X 坐标',
    defaultValue: 320,
    min:  -100,
    max:  740,
    step: 1,
    unit: 'px',
  },
  refreshBtnY: {
    labelCn:      '刷新按钮 Y 坐标',
    description:  '刷新按钮圆心 Y 坐标',
    defaultValue: 900,
    min:  0,
    max:  1384,
    step: 2,
    unit: 'px',
  },
  phaseBtnX: {
    labelCn:      '战斗切换按钮 X 坐标',
    description:  '战斗/商店切换按钮圆心 X 坐标',
    defaultValue: 320,
    min:  -100,
    max:  740,
    step: 1,
    unit: 'px',
  },
  phaseBtnY: {
    labelCn:      '战斗切换按钮 Y 坐标',
    description:  '战斗/商店切换按钮圆心 Y 坐标',
    defaultValue: 780,
    min:  0,
    max:  1384,
    step: 2,
    unit: 'px',
  },
  battleBackBtnX: {
    labelCn:      '战斗返回按钮 X 坐标',
    description:  '战斗结束后“回到商店”按钮中心 X 坐标',
    defaultValue: 320,
    min:  -100,
    max:  740,
    step: 1,
    unit: 'px',
  },
  battleBackBtnY: {
    labelCn:      '战斗返回按钮 Y 坐标',
    description:  '战斗结束后“回到商店”按钮中心 Y 坐标',
    defaultValue: 1250,
    min:  0,
    max:  1384,
    step: 2,
    unit: 'px',
  },
  battleSpeedBtnY: {
    labelCn:      '战斗倍速按钮 Y 坐标',
    description:  '战斗中右上角倍速按钮中心 Y 坐标',
    defaultValue: 84,
    min:  0,
    max:  1384,
    step: 2,
    unit: 'px',
  },
  battleStatsPanelY: {
    labelCn:      '战斗统计面板 Y 坐标',
    description:  '战斗统计弹层面板中心 Y 坐标',
    defaultValue: 760,
    min:  120,
    max:  1300,
    step: 2,
    unit: 'px',
  },
  goldTextCenterX: {
    labelCn:      '当前金币中心 X 坐标',
    description:  '当前金币文字中心 X 坐标',
    defaultValue: 320,
    min:  -100,
    max:  740,
    step: 1,
    unit: 'px',
  },
  goldTextY: {
    labelCn:      '当前金币 Y 坐标',
    description:  '当前金币文字左上角 Y 坐标',
    defaultValue: 958,
    min:  0,
    max:  1384,
    step: 2,
    unit: 'px',
  },
  shopPlayerStatusY: {
    labelCn:      '商店玩家信息 Y 坐标',
    description:  '非战斗玩家信息面板（头像/Lv/HP/EXP）整体 Y 坐标',
    defaultValue: 120,
    min:  0,
    max:  1384,
    step: 2,
    unit: 'px',
  },
  shopPlayerStatusLvY: {
    labelCn:      '玩家等级文本 Y 坐标',
    description:  '非战斗玩家信息面板中 Lv 文本 Y 坐标',
    defaultValue: 70,
    min:  0,
    max:  300,
    step: 1,
    unit: 'px',
  },
  shopPlayerStatusExpBarWidth: {
    labelCn:      '玩家经验条总宽度',
    description:  '非战斗玩家信息面板中经验豆总宽度',
    defaultValue: 120,
    min:  40,
    max:  220,
    step: 1,
    unit: 'px',
  },
  shopPlayerStatusExpBarHeight: {
    labelCn:      '玩家经验条高度',
    description:  '非战斗玩家信息面板中经验豆总高度',
    defaultValue: 30,
    min:  12,
    max:  80,
    step: 1,
    unit: 'px',
  },
  shopPlayerStatusExpBarOffsetX: {
    labelCn:      '玩家经验条X偏移',
    description:  '经验条相对头像中心水平偏移（正值右移）',
    defaultValue: 0,
    min:  -160,
    max:  160,
    step: 1,
    unit: 'px',
  },
  shopPlayerStatusExpBarOffsetY: {
    labelCn:      '玩家经验条Y偏移',
    description:  '经验条相对头像底部垂直偏移（正值下移）',
    defaultValue: 60,
    min:  -80,
    max:  220,
    step: 1,
    unit: 'px',
  },
  dayDebugX: {
    labelCn:      'Day 控件 X 坐标',
    description:  'Day 调试控件容器左上角 X 坐标',
    defaultValue: 8,
    min:  -100,
    max:  740,
    step: 1,
    unit: 'px',
  },
  dayDebugY: {
    labelCn:      'Day 控件 Y 坐标',
    description:  'Day 调试控件容器左上角 Y 坐标',
    defaultValue: 984,
    min:  0,
    max:  1384,
    step: 2,
    unit: 'px',
  },
  tierBorderWidth: {
    labelCn:      '品质描边宽度',
    description:  '商店、背包、战斗区物品品质描边线宽',
    defaultValue: 4,
    min:  1,
    max:  12,
    step: 1,
    unit: 'px',
  },
  gridItemCornerRadius: {
    labelCn:      '格子/装备圆角',
    description:  '战斗区/背包格子背景与装备底框统一圆角大小',
    defaultValue: 10,
    min:  0,
    max:  32,
    step: 1,
    unit: 'px',
  },
  gridCellBorderWidth: {
    labelCn:      '战斗/背包底框边框宽度',
    description:  '战斗区与背包区网格底框边框线宽',
    defaultValue: 1,
    min:  1,
    max:  12,
    step: 1,
    unit: 'px',
  },
  tierColorBronze: {
    labelCn:      '品质色-青铜',
    description:  '青铜品质边框颜色（16进制颜色）',
    defaultValue: 0x6e4b35,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  tierColorSilver: {
    labelCn:      '品质色-白银',
    description:  '白银品质边框颜色（16进制颜色）',
    defaultValue: 0xe2e8f0,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  tierColorGold: {
    labelCn:      '品质色-黄金',
    description:  '黄金品质边框颜色（16进制颜色）',
    defaultValue: 0xfacc15,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  tierColorDiamond: {
    labelCn:      '品质色-钻石',
    description:  '钻石品质边框颜色（16进制颜色）',
    defaultValue: 0x22d3ee,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleColorHp: {
    labelCn:      '战斗色-生命值',
    description:  '战斗中生命值伤害相关统一颜色（跳字/投射）',
    defaultValue: 0xef4444,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleColorHpBar: {
    labelCn:      '战斗色-生命值血条',
    description:  '战斗中生命值血条填充颜色',
    defaultValue: 0xef4444,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleColorHpText: {
    labelCn:      '战斗色-生命值文字',
    description:  '战斗中生命值文本颜色（如 120/300 中的血量数字）',
    defaultValue: 0xffffff,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleColorShield: {
    labelCn:      '战斗色-护盾',
    description:  '战斗中护盾相关统一颜色（护盾条/跳字/投射）',
    defaultValue: 0x3b82f6,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleColorBurn: {
    labelCn:      '战斗色-灼烧',
    description:  '战斗中灼烧相关统一颜色',
    defaultValue: 0xf97316,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleColorPoison: {
    labelCn:      '战斗色-中毒',
    description:  '战斗中中毒相关统一颜色',
    defaultValue: 0xa855f7,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleColorRegen: {
    labelCn:      '战斗色-回复',
    description:  '战斗中治疗/回复相关统一颜色',
    defaultValue: 0x22c55e,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleOrbColorHp: {
    labelCn:      '小球色-生命值伤害',
    description:  '战斗中生命值伤害飞出小球颜色',
    defaultValue: 0xef4444,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleOrbColorShield: {
    labelCn:      '小球色-护盾',
    description:  '战斗中护盾飞出小球颜色',
    defaultValue: 0x3b82f6,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleOrbColorBurn: {
    labelCn:      '小球色-灼烧',
    description:  '战斗中灼烧飞出小球颜色',
    defaultValue: 0xf97316,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleOrbColorPoison: {
    labelCn:      '小球色-中毒',
    description:  '战斗中中毒飞出小球颜色',
    defaultValue: 0xa855f7,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleOrbColorRegen: {
    labelCn:      '小球色-回复',
    description:  '战斗中治疗/回复飞出小球颜色',
    defaultValue: 0x22c55e,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleOrbColorFreeze: {
    labelCn:      '小球色-冻结',
    description:  '战斗中冻结飞出小球颜色',
    defaultValue: 0x8ad8ff,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleOrbColorSlow: {
    labelCn:      '小球色-减速',
    description:  '战斗中减速飞出小球颜色',
    defaultValue: 0x7aa7ff,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleOrbColorHaste: {
    labelCn:      '小球色-加速',
    description:  '战斗中加速飞出小球颜色',
    defaultValue: 0xffea4d,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleTextColorDamage: {
    labelCn:      '跳字色-普通伤害',
    description:  '战斗中普通攻击伤害跳字颜色',
    defaultValue: 0xef4444,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleTextColorCrit: {
    labelCn:      '跳字色-暴击伤害',
    description:  '战斗中暴击伤害跳字颜色',
    defaultValue: 0xffc94d,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleTextColorShield: {
    labelCn:      '跳字色-护盾',
    description:  '战斗中护盾跳字颜色',
    defaultValue: 0x3b82f6,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleTextColorBurn: {
    labelCn:      '跳字色-灼烧',
    description:  '战斗中灼烧伤害跳字颜色',
    defaultValue: 0xf97316,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleTextColorPoison: {
    labelCn:      '跳字色-中毒',
    description:  '战斗中中毒伤害跳字颜色',
    defaultValue: 0xa855f7,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  battleTextColorRegen: {
    labelCn:      '跳字色-回复',
    description:  '战斗中治疗/回复跳字颜色',
    defaultValue: 0x22c55e,
    min:  0x000000,
    max:  0xffffff,
    step: 1,
    unit: 'hex',
  },
  shopAreaBgWidth: {
    labelCn:      '商店背景宽度',
    description:  '商店区域纯色背景宽度',
    defaultValue: 660,
    min:  320,
    max:  900,
    step: 1,
    unit: 'px',
  },
  shopAreaBgHeight: {
    labelCn:      '商店背景高度',
    description:  '商店区域纯色背景高度',
    defaultValue: 328,
    min:  120,
    max:  700,
    step: 1,
    unit: 'px',
  },
  backpackAreaBgWidth: {
    labelCn:      '背包背景宽度',
    description:  '背包区域纯色背景宽度',
    defaultValue: 607,
    min:  320,
    max:  900,
    step: 1,
    unit: 'px',
  },
  backpackAreaBgHeight: {
    labelCn:      '背包背景高度',
    description:  '背包区域纯色背景高度',
    defaultValue: 266,
    min:  120,
    max:  700,
    step: 1,
    unit: 'px',
  },
  itemInfoBottomGapToShop: {
    labelCn:      '信息面板距商店间距',
    description:  '信息面板下边缘到商店上边缘的固定距离',
    defaultValue: 12,
    min:  0,
    max:  240,
    step: 1,
    unit: 'px',
  },
  itemInfoWidth: {
    labelCn:      '物品信息面板宽度',
    description:  '上方面板宽度（支持贴边）',
    defaultValue: 400,
    min:  360,
    max:  640,
    step: 2,
    unit: 'px',
  },
  itemInfoMinH: {
    labelCn:      '物品信息面板最低高度',
    description:  '非小型物品的信息面板最低高度；面板向下对齐，内容超出时向上扩展',
    defaultValue: 240,
    min:  160,
    max:  900,
    step: 2,
    unit: 'px',
  },
  itemInfoMinHSmall: {
    labelCn:      '小型信息面板最低高度',
    description:  '小型(1x1)物品的信息面板最低高度；可单独调小',
    defaultValue: 180,
    min:  120,
    max:  900,
    step: 2,
    unit: 'px',
  },
  gridZoneLabelFontSize: {
    labelCn:      '区域描述文本',
    description:  '商店/战斗区/背包 区域描述文本大小',
    defaultValue: 22,
    min:  10,
    max:  48,
    step: 4,
    unit: 'px',
  },
  shopButtonLabelFontSize: {
    labelCn:      '商店按钮字号',
    description:  '背包/刷新/出售 按钮主文字大小',
    defaultValue: 22,
    min:  10,
    max:  48,
    step: 4,
    unit: 'px',
  },
  phaseButtonLabelFontSize: {
    labelCn:      '战斗切换按钮字号',
    description:  '战斗/商店切换按钮主文字大小',
    defaultValue: 22,
    min:  10,
    max:  48,
    step: 4,
    unit: 'px',
  },
  battleBackButtonLabelFontSize: {
    labelCn:      '回到商店按钮字号',
    description:  '战斗结算页“回到商店”按钮文字大小',
    defaultValue: 30,
    min:  10,
    max:  64,
    step: 4,
    unit: 'px',
  },
  sellButtonSubPriceFontSize: {
    labelCn:      '出售按钮副文字字号',
    description:  '出售按钮下方价格文字大小',
    defaultValue: 16,
    min:  10,
    max:  40,
    step: 4,
    unit: 'px',
  },
  refreshCostFontSize: {
    labelCn:      '刷新费用字号',
    description:  '刷新费用文本字体大小',
    defaultValue: 18,
    min:  10,
    max:  40,
    step: 4,
    unit: 'px',
  },
  goldFontSize: {
    labelCn:      '金币字号',
    description:  '持有金币文本字体大小',
    defaultValue: 20,
    min:  10,
    max:  48,
    step: 4,
    unit: 'px',
  },
  shopPlayerStatusLvFontSize: {
    labelCn:      '玩家等级文本字号',
    description:  '非战斗玩家信息面板中 Lv 文本字体大小',
    defaultValue: 40,
    min:  10,
    max:  80,
    step: 1,
    unit: 'px',
  },
  dayDebugArrowFontSize: {
    labelCn:      '天数箭头字号',
    description:  'Day 调试箭头字体大小',
    defaultValue: 22,
    min:  10,
    max:  48,
    step: 4,
    unit: 'px',
  },
  dayDebugLabelFontSize: {
    labelCn:      '天数字号',
    description:  'Day 调试文本字体大小',
    defaultValue: 18,
    min:  10,
    max:  48,
    step: 4,
    unit: 'px',
  },
  shopItemNameFontSize: {
    labelCn:      '商店名字号',
    description:  '商店物品名称字体大小',
    defaultValue: 16,
    min:  10,
    max:  40,
    step: 4,
    unit: 'px',
  },
  shopItemPriceFontSize: {
    labelCn:      '商店价格字号',
    description:  '商店物品价格字体大小',
    defaultValue: 15,
    min:  10,
    max:  40,
    step: 4,
    unit: 'px',
  },
  shopItemBoughtFontSize: {
    labelCn:      '已购标记字号',
    description:  '商店已购标记字体大小',
    defaultValue: 24,
    min:  10,
    max:  56,
    step: 4,
    unit: 'px',
  },
  itemStatBadgeFontSize: {
    labelCn:      '物品数值标记字号',
    description:  '物品顶部伤害/护盾/回血/灼烧/中毒标记字体大小',
    defaultValue: 20,
    min:  8,
    max:  56,
    step: 4,
    unit: 'px',
  },
  itemTierStarFontSize: {
    labelCn:      '物品星级字号',
    description:  '物品底部星级（★/★★）字体大小',
    defaultValue: 36,
    min:  8,
    max:  72,
    step: 4,
    unit: 'px',
  },
  itemTierStarStrokeWidth: {
    labelCn:      '物品星级描边宽度',
    description:  '物品星级文字描边线宽',
    defaultValue: 5,
    min:  0,
    max:  16,
    step: 1,
    unit: 'px',
  },
  itemTierStarOffsetX: {
    labelCn:      '物品星级X偏移',
    description:  '物品底部等级数字X偏移（负值左移，正值右移）',
    defaultValue: 0,
    min:  -64,
    max:  64,
    step: 1,
    unit: 'px',
  },
  itemTierStarOffsetY: {
    labelCn:      '物品星级Y偏移',
    description:  '物品底部等级数字Y偏移（负值上移，正值下移）',
    defaultValue: 0,
    min:  -64,
    max:  64,
    step: 1,
    unit: 'px',
  },
  itemStatBadgeOffsetY: {
    labelCn:      '物品数值标记Y偏移',
    description:  '物品顶部数值标记整体Y偏移（负值上移，正值下移）',
    defaultValue: 0,
    min:  -64,
    max:  64,
    step: 1,
    unit: 'px',
  },
  itemInfoNameFontSize: {
    labelCn:      '信息名称字号',
    description:  '上方面板名称字体大小',
    defaultValue: 22,
    min:  10,
    max:  56,
    step: 4,
    unit: 'px',
  },
  itemInfoTierFontSize: {
    labelCn:      '信息品质标字号',
    description:  '上方面板品质标签字体大小',
    defaultValue: 14,
    min:  10,
    max:  40,
    step: 4,
    unit: 'px',
  },
  itemInfoPriceFontSize: {
    labelCn:      '信息价格字号',
    description:  '上方面板价格字体大小',
    defaultValue: 20,
    min:  10,
    max:  56,
    step: 4,
    unit: 'px',
  },
  itemInfoPriceCornerFontSize: {
    labelCn:      '信息右下价格字号',
    description:  '上方面板右下角价格字体大小',
    defaultValue: 20,
    min:  10,
    max:  56,
    step: 4,
    unit: 'px',
  },
  itemInfoCooldownFontSize: {
    labelCn:      '信息冷却字号',
    description:  '上方面板右上角冷却字体大小',
    defaultValue: 20,
    min:  10,
    max:  56,
    step: 4,
    unit: 'px',
  },
  itemInfoDescFontSize: {
    labelCn:      '信息描述字号',
    description:  '上方面板描述字体大小',
    defaultValue: 16,
    min:  10,
    max:  40,
    step: 4,
    unit: 'px',
  },
  itemInfoSimpleDescFontSize: {
    labelCn:      '信息简版字号',
    description:  '上方面板简版（核心数值/速度/玩法）字体大小',
    defaultValue: 16,
    min:  10,
    max:  40,
    step: 4,
    unit: 'px',
  },
  synthTitleFontSize: {
    labelCn:      '合成标题字号',
    description:  '合成信息层标题字体大小',
    defaultValue: 36,
    min:  12,
    max:  80,
    step: 4,
    unit: 'px',
  },
  synthNameFontSize: {
    labelCn:      '合成名称字号',
    description:  '合成信息层物品名称字体大小',
    defaultValue: 24,
    min:  12,
    max:  64,
    step: 4,
    unit: 'px',
  },
  battleZoneExpandMs: {
    labelCn:      '战斗区扩展动画时长',
    description:  '切换天数时战斗区向两侧扩展的过渡动画时长',
    defaultValue: 400,
    min:  100,
    max:  2000,
    step: 50,
    unit: 'ms',
  },
  shopToBattleTransitionMs: {
    labelCn:      '开战转场时长',
    description:  '商店点击战斗后，切场前的转场总时长',
    defaultValue: 420,
    min:  100,
    max:  2000,
    step: 20,
    unit: 'ms',
  },
  shopToBattleBackpackDropPx: {
    labelCn:      '开战背包下落距离',
    description:  '开战转场时背包区域向下移动的距离',
    defaultValue: 220,
    min:  0,
    max:  900,
    step: 2,
    unit: 'px',
  },
  shopToBattleBackpackAlpha: {
    labelCn:      '开战背包目标透明度',
    description:  '开战转场结束时背包区域透明度',
    defaultValue: 0,
    min:  0,
    max:  1,
    step: 0.01,
    unit: 'alpha',
  },
  shopToBattleButtonsAlpha: {
    labelCn:      '开战按钮目标透明度',
    description:  '开战转场结束时底部按钮与调试Day区透明度',
    defaultValue: 0,
    min:  0,
    max:  1,
    step: 0.01,
    unit: 'alpha',
  },
  battleIntroFadeInMs: {
    labelCn:      '战斗入场淡入时长',
    description:  '切到战斗场景后主角/敌人/UI整体淡入时长',
    defaultValue: 360,
    min:  0,
    max:  2000,
    step: 20,
    unit: 'ms',
  },
  battleToShopTransitionMs: {
    labelCn:      '回店转场时长',
    description:  '战斗结束点击回到商店后的淡出转场时长',
    defaultValue: 320,
    min:  80,
    max:  2000,
    step: 20,
    unit: 'ms',
  },
  battleSettlementDelayMs: {
    labelCn:      '结算弹窗延迟',
    description:  '战斗结束且表现播放完后，额外等待再弹出结算页',
    defaultValue: 1000,
    min:  0,
    max:  3000,
    step: 20,
    unit: 'ms',
  },
  shopPassiveJumpMoveMs: {
    labelCn:      '被动跳字移动时长',
    description:  '备战区被动跳字向上移动所用时间',
    defaultValue: 220,
    min:  0,
    max:  2000,
    step: 20,
    unit: 'ms',
  },
  shopPassiveJumpHoldMs: {
    labelCn:      '被动跳字停留时长',
    description:  '备战区被动跳字到顶后保持不动的时间',
    defaultValue: 180,
    min:  0,
    max:  2000,
    step: 20,
    unit: 'ms',
  },
  shopPassiveJumpFadeMs: {
    labelCn:      '被动跳字淡出时长',
    description:  '备战区被动跳字透明淡出所用时间',
    defaultValue: 220,
    min:  0,
    max:  2000,
    step: 20,
    unit: 'ms',
  },
  shopPassiveJumpFontSize: {
    labelCn:      '被动跳字字号',
    description:  '备战区被动跳字的字体大小',
    defaultValue: 26,
    min:  10,
    max:  72,
    step: 1,
    unit: 'px',
  },
  autoPackThrottleMs: {
    labelCn:      'AutoPack 节流窗口',
    description:  '同一背包状态下 AutoPack 结果复用窗口，减少拖拽高频计算',
    defaultValue: 50,
    min:  0,
    max:  300,
    step: 5,
    unit: 'ms',
  },
  toastEnabled: {
    labelCn:      '显示 Toast 提示',
    description:  '总开关：是否显示商店失败路径的 toast 提示',
    defaultValue: 1,
    min:  0,
    max:  1,
    step: 1,
    unit: '',
  },
  toastShowNoGoldBuy: {
    labelCn:      '金币不足-购买',
    description:  '金币不足导致无法购买时是否显示 toast',
    defaultValue: 1,
    min:  0,
    max:  1,
    step: 1,
    unit: '',
  },
  toastShowNoGoldRefresh: {
    labelCn:      '金币不足-刷新',
    description:  '金币不足导致无法刷新时是否显示 toast',
    defaultValue: 1,
    min:  0,
    max:  1,
    step: 1,
    unit: '',
  },
  toastShowBackpackFullBuy: {
    labelCn:      '背包满-购买',
    description:  '背包已满导致无法购买时是否显示 toast',
    defaultValue: 1,
    min:  0,
    max:  1,
    step: 1,
    unit: '',
  },
  toastShowBackpackFullTransfer: {
    labelCn:      '背包满-转移',
    description:  '背包已满导致无法转移到背包时是否显示 toast',
    defaultValue: 1,
    min:  0,
    max:  1,
    step: 1,
    unit: '',
  },
  toastShowFatigueStart: {
    labelCn:      '加时赛-风暴来袭',
    description:  '进入超时扣血阶段时是否显示“加时赛风暴来袭”toast',
    defaultValue: 1,
    min:  0,
    max:  1,
    step: 1,
    unit: '',
  },
}

const _projectDefaults = projectDebugDefaults as Record<string, number>
for (const [key, val] of Object.entries(_projectDefaults)) {
  const def = CONFIG_DEFS[key]
  if (!def) continue
  if (!Number.isFinite(val)) continue
  def.defaultValue = normalizeConfigNumber(key, Number(val), def)
}

// ---- 读写 ----

/** 读取配置值（localStorage > 默认值） */
export function getConfig(key: string): number {
  const def = CONFIG_DEFS[key]
  const raw = localStorage.getItem(STORAGE_PREFIX + key)
  if (raw !== null) {
    const n = Number(raw)
    if (!Number.isNaN(n)) {
      return normalizeConfigNumber(key, n, def)
    }
  }
  return normalizeConfigNumber(key, def?.defaultValue ?? 0, def)
}

/** 写入配置值并广播到同源的其他页面（例如正在运行的游戏） */
export function setConfig(key: string, value: number): void {
  const def = CONFIG_DEFS[key]
  const v = normalizeConfigNumber(key, value, def)
  localStorage.setItem(STORAGE_PREFIX + key, String(v))
  try {
    _getChannel().postMessage({ key, value: v })
  } catch { /* BroadcastChannel 不支持时静默失败 */ }
}

/** 重置某个参数到默认值 */
export function resetConfig(key: string): void {
  localStorage.removeItem(STORAGE_PREFIX + key)
  const def = CONFIG_DEFS[key]?.defaultValue ?? 0
  try {
    _getChannel().postMessage({ key, value: def })
  } catch {}
}

/** 重置所有参数到默认值 */
export function resetAllConfig(): void {
  for (const key of Object.keys(CONFIG_DEFS)) resetConfig(key)
}

export function clearStoredConfig(): void {
  const keys: string[] = []
  for (let i = 0; i < localStorage.length; i++) {
    const k = localStorage.key(i)
    if (k && k.startsWith(STORAGE_PREFIX)) keys.push(k)
  }
  for (const k of keys) localStorage.removeItem(k)
}

export function getConfigSnapshot(): Record<string, number> {
  const out: Record<string, number> = {}
  for (const key of Object.keys(CONFIG_DEFS)) {
    out[key] = getConfig(key)
  }
  return out
}

// ---- 订阅（供游戏侧调用）----

type ConfigChangeCallback = (key: string, value: number) => void

const _listeners: Set<ConfigChangeCallback> = new Set()

/** 订阅来自调试页的实时更新，返回取消订阅函数 */
export function onConfigChange(cb: ConfigChangeCallback): () => void {
  _listeners.add(cb)
  return () => _listeners.delete(cb)
}

// ---- 内部 BroadcastChannel ----

let _channel: BroadcastChannel | null = null

function _getChannel(): BroadcastChannel {
  if (!_channel) {
    _channel = new BroadcastChannel(BC_NAME)
    _channel.onmessage = (e: MessageEvent<{ key: string; value: number }>) => {
      const { key, value } = e.data
      const def = CONFIG_DEFS[key]
      const v = def ? Math.max(def.min, Math.min(def.max, value)) : value
      // 同步写入 localStorage，让下次 getConfig() 也返回新值
      localStorage.setItem(STORAGE_PREFIX + key, String(v))
      // 通知所有监听器
      for (const cb of _listeners) cb(key, v)
    }
  }
  return _channel
}

// 初始化 channel 以便监听来自其他标签页的更新
_getChannel()
